kafka.bootstrap.servers=localhost:9092
# Kafka Channels
# AgentTask
mp.messaging.outgoing.agent-tasks.connector=smallrye-kafka
mp.messaging.outgoing.agent-tasks.topic=agent-tasks
mp.messaging.outgoing.agent-tasks.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer
mp.messaging.outgoing.agent-tasks.acks=${KAFKA_AGENT_TASKS_ACKS:all}
mp.messaging.outgoing.agent-tasks.retries=${KAFKA_AGENT_TASKS_RETRIES:5}
mp.messaging.outgoing.agent-tasks.enable.idempotence=${KAFKA_AGENT_TASKS_IDEMPOTENCE:true}
mp.messaging.outgoing.agent-tasks.max.in.flight.requests.per.connection=${KAFKA_AGENT_TASKS_MAX_IN_FLIGHT:5}
mp.messaging.outgoing.agent-tasks.delivery.timeout.ms=${KAFKA_AGENT_TASKS_DELIVERY_TIMEOUT_MS:120000}
# AgentEvent
mp.messaging.incoming.agent-events.connector=smallrye-kafka
mp.messaging.incoming.agent-events.topic=agent-events
mp.messaging.incoming.agent-events.value.deserializer=org.acme.gateway.models.AgentEventDeserializer
mp.messaging.incoming.agent-events.value.deserializer.type=org.acme.gateway.models.AgentEvent

quarkus.websocket.next.auto-ping-interval=20S

quarkus.jackson.property-naming-strategy=SNAKE_CASE

quarkus.rest-client."org.acme.gateway.services.AIService".url=http://localhost:8000

# PostgreSQL Datasource
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=root
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5433/network_design
quarkus.hibernate-orm.database.generation=update

# OIDC OAuth
quarkus.oidc.auth-server-url="http://localhost:8180/realms/cx-sol-build"
quarkus.oidc.client-id=gateway
quarkus.oidc.credentials.secret=secret
quarkus.oidc.authentication.enabled=true
quarkus.oidc.token.required=true
quarkus.http.auth.permission.authenticated.paths=/api/*
quarkus.http.auth.permission.authenticated.policy=authenticated
