# Kafka Channels
quarkus.kafka.devservices.port=9092
quarkus.http.port=8080

mp.messaging.outgoing.agent-tasks.connector=smallrye-kafka
mp.messaging.outgoing.agent-tasks.topic=agent-tasks

mp.messaging.incoming.agent-events.connector=smallrye-kafka
mp.messaging.incoming.agent-events.topic=agent-events
