# Kafka Channels
mp.messaging.outgoing.agent-tasks.connector=smallrye-kafka
mp.messaging.outgoing.agent-tasks.topic=agent-tasks
mp.messaging.outgoing.agent-tasks.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer
mp.messaging.incoming.agent-events.connector=smallrye-kafka
mp.messaging.incoming.agent-events.topic=agent-events
mp.messaging.incoming.agent-events.value.deserializer=org.acme.gateway.models.AgentEventDeserializer
# Set target class for deserialization
mp.messaging.incoming.agent-events.value.deserializer.type=org.acme.gateway.models.AgentEvent
